#ifndef REALSIM_VERSION_H
#define REALSIM_VERSION_H

#define REALSIM_VERSION_MAJOR   0
#define REALSIM_VERSION_MINOR   5
#define REALSIM_VERSION_PATCH   8

#define REALSIM_VERSION_NUMBER 0x000508
#define REALSIM_VERSION_STRING  "0.5.8"

#endif