#ifndef REALSIM_VERSION_H
#define REALSIM_VERSION_H

#define REALSIM_VERSION_MAJOR   0
#define REALSIM_VERSION_MINOR   6
#define REALSIM_VERSION_PATCH   0

#define REALSIM_VERSION_NUMBER 0x000600
#define REALSIM_VERSION_STRING  "0.6.0"

#endif