"""
sumo_route_points.py - the ego route as a POLYLINE, for whoever steers in CARLA.

sumo_ego.py puts the ego on a route in SUMO, and a route in SUMO is a list of
edge ids. Nothing in CARLA can steer to an edge id. A driver that tracks a path
-- the bridge's pure-pursuit EgoDriver, or a Python controller built on CARLA's
BasicAgent -- needs the same route as (x, y) points, and that is the only thing
this produces.

The two must come from ONE source or they are not the same route. So the edges
are resolved exactly the way sumo_ego resolves them: by id, out of the map
bundle's own demand, never from a list an application keeps. sumo_ego's own
docstring says why -- an app that copies map data owns a copy that goes stale
the moment the bundle is republished, and MLK once carried a 71-edge route
pasted into a Python file beside the route file it came from.

The polyline is stamped with a fingerprint of (network, route id, edges), and
--check compares it. That is what catches the failure this exists to prevent:
regenerate one artifact and forget the other, and SUMO drives one corridor while
CARLA steers another. Its first symptom is not a visible swerve -- it is the
ego's next-signal fields going empty, which an eco-driving controller reads as
"no signal in sight" and silently plans against.

Needs sumolib (SUMO's own Python library) for the network; sumo_ego does not,
which is why this is a separate file rather than another flag on it.

Usage
-----
  # write the EgoRoutePoints block into a scenario yaml
  python sumo_route_points.py --sumocfg ~/.fixs/maps/<map>/sumo/<map>.sumocfg \\
                              --route-from route1 --yaml config_..._L2.yaml

  # is the block still the route the bundle defines?
  python sumo_route_points.py --sumocfg ... --route-from route1 \\
                              --yaml config_..._L2.yaml --check

  # just print the points
  python sumo_route_points.py --sumocfg ... --route-from route1
"""
from __future__ import annotations

import argparse
import hashlib
import math
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sumo_ego import route_from_bundle  # noqa: E402  the one route of record

BLOCK_BEGIN = "  # >>> EgoRoutePoints -- generated by sumo_route_points.py"
BLOCK_END = "  # <<< EgoRoutePoints"

# The driver re-densifies to ~3 m anyway, so points that add no shape are dropped.
# Keeping them costs nothing but makes the block unreadable and hides real geometry.
DEFAULT_MAX_GAP_M = 30.0
DEFAULT_MAX_HEADING_DEV_DEG = 3.0


def _split_list(value):
    return [p.strip() for p in (value or "").split(",") if p.strip()]


def _abs_from(base_dir, name):
    p = Path(name)
    return str(p if p.is_absolute() else (base_dir / p).resolve())


def scenario_inputs(sumocfg):
    """(net file, [route files]) named by a sumocfg, resolved against it."""
    cfg = Path(sumocfg).resolve()
    root = ET.parse(cfg).getroot()

    net = root.find("./input/net-file")
    if net is None or not net.get("value"):
        raise SystemExit(f"no <net-file> in {cfg}")

    routes = root.find("./input/route-files")
    route_files = _split_list(routes.get("value", "")) if routes is not None else []

    return (_abs_from(cfg.parent, net.get("value")),
            [_abs_from(cfg.parent, r) for r in route_files])


def fingerprint(net_file, route_id, edges):
    """Short hash of everything the polyline depends on.

    The network is in it deliberately: the same route id on a republished map
    can name a different corridor, and an edge-only hash would call that a match.
    """
    joined = "|".join([Path(net_file).name, route_id] + list(edges))
    return hashlib.sha1(joined.encode("utf-8")).hexdigest()[:8]


def solve_lane_chain(net, edges, start_lane_index):
    """Pick one lane per route edge such that every step is a real connection.

    Returns [(lane, connection_to_next_edge), ...], one per edge, wrapping from
    the last edge back to the first. Raises when no such chain exists -- which
    means the ego cannot drive these edges from this start lane, and no amount
    of geometry will make the pose feed back into SUMO coherently.

    TAKING A FIXED LANE INDEX IS WRONG, and looks harmless on a corridor whose
    lanes all run through. A lane only reaches the edges its connections lead
    to. On MLK, `E1_0 -> 51066109#3_1` and `E1_1 -> 51066109#3_2`; NOTHING from
    E1 reaches 51066109#3_0, which is fed only by the 19491642 approach. Emitting
    lane 0 of every edge put the polyline on 51066109#3_0 and then on
    51066109#3.42_0 -- a lane whose only connection goes to 81250839, not to the
    route's own next edge.

    That is not a cosmetic offset, it is a trajectory SUMO cannot reproduce.
    Driving it and feeding the pose back with moveToXY left SUMO holding a
    vehicle in a lane unreachable from its own route: it refused to place it
    (empty lane id, odometer frozen for 5 ticks), then re-anchored 17.2 m
    BACKWARDS when a placement finally resolved. A next-signal cache indexed by
    that odometer then named signals the ego had already passed.

    A GREEDY WALK IS NOT ENOUGH either. One lane can hold several connections to
    the same next edge -- 51066109#1_1 reaches BOTH E1_1 and E1_2 -- and only one
    continues the route: E1_2 leads to 183526664 and dies two edges later. So the
    chain is SEARCHED, and only a chain that survives every edge is accepted.
    """

    def successors(lane, next_id):
        out = [c for c in lane.getOutgoing()
               if c.getToLane().getEdge().getID() == next_id]
        # Fewest lane changes first, then lowest lane index -- deterministic, and
        # it prefers staying put over drifting across the carriageway.
        return sorted(out, key=lambda c: (c.getToLane().getIndex() != lane.getIndex(),
                                          c.getToLane().getIndex()))

    first = net.getEdge(edges[0])
    start = first.getLane(min(start_lane_index, first.getLaneNumber() - 1))

    dead: set[tuple[int, str]] = set()          # (edge index, lane id) proven hopeless

    def walk(index, lane, acc):
        if index == len(edges) - 1:             # last edge: must close the loop
            for c in successors(lane, edges[0]):
                if c.getToLane().getID() == start.getID():
                    return acc + [(lane, c)]
            # a loop that cannot close is still usable one-way; take any exit
            outs = successors(lane, edges[0])
            return acc + [(lane, outs[0])] if outs else None
        for c in successors(lane, edges[index + 1]):
            nxt = c.getToLane()
            key = (index + 1, nxt.getID())
            if key in dead:
                continue
            got = walk(index + 1, nxt, acc + [(lane, c)])
            if got is not None:
                return got
            dead.add(key)
        return None

    chain = walk(0, start, [])
    if chain is None:
        raise SystemExit(
            f"no drivable lane chain from '{start.getID()}'. Every candidate runs "
            f"into an edge its lane has no connection to. Try a different "
            f"--lane-index, or a route the ego can actually drive in SUMO."
        )
    return chain


def build_points(net_file, edges, start_lane_index, quiet=False):
    """edges -> lane-centreline points [(x, y), ...] in SUMO coordinates.

    Junction interiors come from each connection's internal ("via") lane. Left
    out, the polyline jumps from one edge's end to the next edge's start and cuts
    the corner at every turn -- on the MLK corridor 191 of 703 raw points are
    junction interior, i.e. most of the shape at intersections. On a U-turn loop
    the interior IS the manoeuvre, so omitting it removes the turn entirely.

    The frame is SUMO's, unconverted: the bridge's setEgoRoute flips y into the
    CARLA frame itself, so nothing here should know about CARLA coordinates.
    """
    import sumolib  # only this step needs it; callers that never build must not pay

    net = sumolib.net.readNet(str(net_file), withInternal=True)

    edges = list(edges)
    if len(edges) > 1 and edges[0] == edges[-1]:
        edges = edges[:-1]  # the list closes the loop; the wrap in walk() reopens it

    chain = solve_lane_chain(net, edges, start_lane_index)

    points: list[tuple[float, float]] = []
    lanes_used: list[str] = []
    for lane, connection in chain:
        lanes_used.append(lane.getID())
        points.extend(lane.getShape())
        via_lane_id = connection.getViaLaneID()
        if via_lane_id:
            points.extend(net.getLane(via_lane_id).getShape())

    if not quiet:
        changes = sum(1 for a, b in zip(chain, chain[1:])
                      if a[1].getToLane().getIndex() != b[0].getIndex())
        print(f"  ego route: {len(edges)} edges, start lane {lanes_used[0]}, "
              f"{changes} lane change(s)")
        print(f"    lane indices: "
              f"{' '.join(l.rsplit('_', 1)[1] for l in lanes_used)}")

    return [(float(x), float(y)) for x, y in points]


def decimate(points, max_gap_m=DEFAULT_MAX_GAP_M,
             max_heading_dev_deg=DEFAULT_MAX_HEADING_DEV_DEG):
    """Drop points that add no shape: the driver re-densifies to ~3 m anyway."""
    if len(points) < 3:
        return list(points)

    kept = [points[0]]
    last_heading = None
    for point in points[1:-1]:
        dx, dy = point[0] - kept[-1][0], point[1] - kept[-1][1]
        distance = math.hypot(dx, dy)
        if distance < 1e-6:
            continue
        heading = math.atan2(dy, dx)
        if last_heading is None:
            last_heading = heading
        deviation = abs(math.degrees(
            math.atan2(math.sin(heading - last_heading), math.cos(heading - last_heading))
        ))
        if deviation >= max_heading_dev_deg or distance >= max_gap_m:
            kept.append(point)
            last_heading = heading
    kept.append(points[-1])
    return kept


def block_text(points, net_file, route_id, edges, lane_index, per_line=6):
    """The generated yaml block, markers included."""
    length_m = sum(math.dist(points[i], points[i + 1]) for i in range(len(points) - 1))
    lines = [
        BLOCK_BEGIN,
        f"  #     route '{route_id}' of {Path(net_file).name}: {len(edges)} edges,"
        f" {len(points)} points, {length_m:.0f} m, departing lane {lane_index},"
        f" then the lane each connection leads to. SUMO coordinates.",
        f"  #     route-fingerprint: {fingerprint(net_file, route_id, edges)}",
        "  EgoRoutePoints: [",
    ]
    for start in range(0, len(points), per_line):
        chunk = points[start:start + per_line]
        row = ", ".join(f"[{x:.1f}, {y:.1f}]" for x, y in chunk)
        lines.append(f"    {row},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("  ]")
    lines.append(BLOCK_END)
    return "\n".join(lines)


def _block_bounds(lines):
    """(begin, end) indices of the generated block, or None when absent.

    Matched on the marker's leading text, not the whole line, so the comment can
    name a different generator without the block becoming unfindable.
    """
    begin = end = None
    for i, line in enumerate(lines):
        if begin is None and line.startswith("  # >>> EgoRoutePoints"):
            begin = i
        elif line.startswith("  # <<< EgoRoutePoints"):
            end = i
            break
    return None if begin is None or end is None else (begin, end)


def write_block(yaml_path, points, net_file, route_id, edges, lane_index):
    """Rewrite the yaml's EgoRoutePoints block in place."""
    path = Path(yaml_path)
    original = path.read_text(encoding="utf-8").splitlines()
    bounds = _block_bounds(original)
    if bounds is None:
        raise SystemExit(
            f"{path.name} has no EgoRoutePoints markers. Add these two lines "
            f"around the block for this to own it:\n"
            f"    {BLOCK_BEGIN}\n    {BLOCK_END}"
        )
    begin, end = bounds
    text = block_text(points, net_file, route_id, edges, lane_index)
    updated = original[:begin] + text.splitlines() + original[end + 1:]
    path.write_text("\n".join(updated) + "\n", encoding="utf-8")
    print(f"  route points: {len(points)} -> {path.name}")


def check_block(yaml_path, net_file, route_id, edges):
    """Is the yaml's polyline still this route on this network? Exit code."""
    path = Path(yaml_path)
    if not path.is_file():
        print(f"[check] no {path}; nothing to check.")
        return 0

    expected = fingerprint(net_file, route_id, edges)
    for line in path.read_text(encoding="utf-8").splitlines():
        if "route-fingerprint:" in line:
            found = line.split("route-fingerprint:", 1)[1].strip()
            if found == expected:
                print(f"[check] {path.name} matches route '{route_id}' of "
                      f"{Path(net_file).name} ({expected}).")
                return 0
            print(
                f"[check] STALE: {path.name} was generated from {found}, the "
                f"bundle's route '{route_id}' is now {expected}.\n"
                f"        SUMO would drive one corridor while CARLA steers "
                f"another. Regenerate with this script, without --check."
            )
            return 1

    print(f"[check] {path.name} carries no route-fingerprint; generate it first.")
    return 1


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sumocfg", required=True,
                    help="the map bundle's sumocfg; names the network and the demand")
    ap.add_argument("--route-from", metavar="ID",
                    help="take the ego edges from this route id in the bundle's demand")
    ap.add_argument("--route-edges", metavar="'E1 E2 ...'",
                    help="edges verbatim, for a route the bundle does not define")
    ap.add_argument("--lane-index", type=int, default=0,
                    help="departing lane; 0 = rightmost, matching departLane=first")
    ap.add_argument("--yaml", help="scenario yaml whose EgoRoutePoints block to write")
    ap.add_argument("--check", action="store_true",
                    help="do not write; report whether --yaml is still this route")
    ap.add_argument("--max-gap", type=float, default=DEFAULT_MAX_GAP_M)
    ap.add_argument("--max-heading-dev", type=float, default=DEFAULT_MAX_HEADING_DEV_DEG)
    opt = ap.parse_args(argv)

    if not opt.route_from and not opt.route_edges:
        raise SystemExit("one of --route-from / --route-edges is required")

    net_file, route_files = scenario_inputs(opt.sumocfg)
    edges = (opt.route_edges.split() if opt.route_edges
             else route_from_bundle(route_files, opt.route_from))
    if not edges:
        raise SystemExit("the ego route is empty")
    route_id = opt.route_from or "(edges given)"

    if opt.check:
        if not opt.yaml:
            raise SystemExit("--check needs --yaml")
        return check_block(opt.yaml, net_file, route_id, edges)

    points = decimate(build_points(net_file, edges, opt.lane_index),
                      opt.max_gap, opt.max_heading_dev)

    if opt.yaml:
        write_block(opt.yaml, points, net_file, route_id, edges, opt.lane_index)
    else:
        print(block_text(points, net_file, route_id, edges, opt.lane_index))
    return 0


if __name__ == "__main__":
    sys.exit(main())
