#!/usr/bin/env python
"""Is a scenario's EgoRoutePoints a path the ego can actually drive in SUMO?

An externally-driven ego is placed in SUMO by moveToXY, i.e. by coordinates. SUMO
then has to decide which lane those coordinates mean, and a lane is only reachable
from the lanes whose connections lead to it. If the polyline runs down a lane the
ego cannot legally have entered, SUMO is holding a vehicle in a lane unreachable
from its own route -- and it stops being able to answer the questions everything
downstream depends on.

Measured on mlk_eco_driving, where the route geometry was generated by applying a
fixed lane index to every edge:

    E1_0 -> 51066109#3_1     and     E1_1 -> 51066109#3_2
    nothing from E1 reaches  51066109#3_0
    (51066109#3_0 is fed only by :202587081_4_0 and 19491642_0)

The polyline ran down 51066109#3_0 anyway. SUMO refused to place the vehicle for
five ticks (empty lane id, odometer frozen), then re-anchored it 17.2 m BACKWARDS.
The cached next-signal list is indexed by that odometer, so every later distance
was biased ~21.7 m, the cache named signals the ego had already passed, the signal
head came out belonging to a different signal, the application stopped recognising
the movement, and it released the ego to free-flow speed -- into the car ahead.

None of that is visible while it happens. This check makes it visible before the
run starts, in about a second.

    python check_ego_route.py --config <scenario.yaml> --net <net.xml>

Exit status is 0 when the route is drivable, 1 when it is not.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass


@dataclass
class Violation:
    """One illegal step in the lane sequence the polyline traverses."""
    point_index: int
    xy: tuple[float, float]
    from_lane: str
    to_lane: str
    from_lane_reaches: list[str]
    to_lane_fed_by: list[str]

    def __str__(self) -> str:
        return (
            f"point {self.point_index} ({self.xy[0]:.1f}, {self.xy[1]:.1f}): "
            f"{self.from_lane} -> {self.to_lane} is not a connection\n"
            f"      {self.from_lane} reaches {self.from_lane_reaches or ['nothing']}\n"
            f"      {self.to_lane} is fed by {self.to_lane_fed_by or ['nothing']}"
        )


def load_points_from_config(config_path) -> list[tuple[float, float]]:
    """The EgoRoutePoints block, read textually.

    Not via a YAML parser on purpose: the block is machine-generated between
    marker comments and the surrounding file carries `#pragma once` and other
    non-YAML noise in the wild. Reading the one block we care about is more
    robust than requiring the whole file to parse.
    """
    text = open(config_path, encoding="utf-8", errors="replace").read()
    match = re.search(r"EgoRoutePoints:\s*\[(.*?)\n\s*\]", text, re.S)
    if not match:
        return []
    return [(float(a), float(b))
            for a, b in re.findall(r"\[\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\]", match.group(1))]


def _successors(lane) -> set[str]:
    """Lanes reachable in one step, INCLUDING junction interiors.

    A connection reports only its destination lane; the internal lane it runs
    through is the separate `via`. A polyline that draws junction shapes -- which
    it should, or it cuts every corner -- therefore steps
    approach -> via -> destination, and a check that only knows about
    getToLane() calls the first of those illegal. Both are accepted here, so the
    check works whether or not the geometry includes the interior.
    """
    out: set[str] = set()
    for connection in lane.getOutgoing():
        via = connection.getViaLaneID()
        if via:
            out.add(via)
        out.add(connection.getToLane().getID())
    return out


# How many connections may lie between two consecutive SAMPLES before the gap is
# treated as a genuine break rather than decimation. The polyline keeps a point
# every ~30 m at most; junction interiors and short connector edges are often
# shorter than that, so a legal route can skip a few lanes between samples.
_MAX_HOPS = 6


def _reachable_within(net, lane, target_id: str, max_hops: int) -> bool:
    """Is `target_id` reachable from `lane` in at most `max_hops` connections?"""
    frontier = {lane.getID()}
    seen = {lane.getID()}
    for _ in range(max_hops):
        nxt: set[str] = set()
        for lane_id in frontier:
            try:
                here = net.getLane(lane_id)
            except Exception:
                continue
            for successor in _successors(here):
                if successor == target_id:
                    return True
                if successor not in seen:
                    seen.add(successor)
                    nxt.add(successor)
        if not nxt:
            return False
        frontier = nxt
    return False


def check_ego_route(points, net, snap_tol_m: float = 3.0) -> list[Violation]:
    """Walk the polyline as SUMO sees it. Empty list means it is drivable.

    A point is NOT committed to one lane. Junction interiors overlap -- several
    connections' internal lanes occupy the same tarmac -- so the nearest lane to a
    sample is frequently a neighbouring movement's, and committing to it invents
    illegal steps that are purely an artefact of snapping.

    Instead every lane within tolerance is a candidate, and the walk carries the
    SET of lanes the ego could consistently be on. The next sample's candidates
    are filtered to those reachable from some current candidate; if that leaves
    nothing, no assignment of lanes to samples can explain the polyline and the
    step is a genuine violation.
    """
    # candidates per sample, nearest first, off-network samples dropped
    candidates: list[tuple[int, tuple[float, float], list]] = []
    for index, (x, y) in enumerate(points):
        # No includeJunctions=True. It only selects which shape the distance is
        # measured against, and on a net read withInternal=True sumolib blows up
        # inside it -- lane.getShape(True) calls self._edge.isSpecial() where
        # _edge is still a plain string for internal lanes
        # ("'str' object has no attribute '_function'"). Internal lanes are
        # returned as candidates either way, which is what this needs.
        near = net.getNeighboringLanes(x, y, snap_tol_m)
        if not near:
            continue
        lanes = [lane for lane, _dist in sorted(near, key=lambda pair: pair[1])]
        candidates.append((index, (x, y), lanes))

    violations: list[Violation] = []
    if not candidates:
        return violations

    possible = {lane.getID() for lane in candidates[0][2]}
    for index, xy, lanes in candidates[1:]:
        here = {lane.getID() for lane in lanes}
        # staying put is always legal; otherwise reach it within a few hops. The
        # polyline is DECIMATED (a point every ~30 m at most), so consecutive
        # samples can sit several short lanes apart on a perfectly legal route.
        nxt = {
            lane_id for lane_id in here
            if lane_id in possible
            or any(lane_id in _successors(net.getLane(p)) for p in possible)
            or any(_reachable_within(net, net.getLane(p), lane_id, _MAX_HOPS)
                   for p in possible)
        }
        if nxt:
            possible = nxt
            continue

        # nothing consistent: report against the most plausible pair
        a_id = sorted(possible)[0]
        b_id = lanes[0].getID()
        fed_by = [lane.getID()
                  for edge in net.getEdges(withInternal=True)
                  for lane in edge.getLanes()
                  if b_id in _successors(lane)]
        violations.append(Violation(index, xy, a_id, b_id,
                                    sorted(_successors(net.getLane(a_id))),
                                    sorted(fed_by)))
        possible = here          # resynchronise and keep checking the rest
    return violations


def check_config(config_path, net_path, snap_tol_m: float = 3.0):
    """(violations, point_count). violations is None when there is nothing to check."""
    import sumolib

    points = load_points_from_config(config_path)
    if not points:
        return None, 0
    net = sumolib.net.readNet(str(net_path), withInternal=True, withConnections=True)
    return check_ego_route(points, net, snap_tol_m), len(points)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--config", required=True, help="scenario yaml holding EgoRoutePoints")
    ap.add_argument("--net", required=True, help="the SUMO .net.xml it is driven on")
    ap.add_argument("--tolerance", type=float, default=3.0,
                    help="metres a point may sit from a lane and still count as on it")
    args = ap.parse_args(argv)

    violations, count = check_config(args.config, args.net, args.tolerance)
    if violations is None:
        print("no EgoRoutePoints in this config - nothing to check")
        return 0
    if not violations:
        print(f"ego route OK: {count} points, every step is a real connection")
        return 0

    print(f"ego route NOT DRIVABLE: {len(violations)} illegal step(s) in {count} points\n")
    for v in violations:
        print(f"  {v}")
    print("\nThe ego cannot legally reach these lanes, so SUMO cannot place it "
          "there coherently.\nRegenerate the route so every step follows a "
          "connection (prepare_scenario.py).")
    return 1


if __name__ == "__main__":
    sys.exit(main())
